
export interface Employee {
  id: string;
  pin: string; // Fingerspot ID
  nik: string;
  name: string;
  division: string;
  position: string;
  joinDate: string;
  birthPlace: string;
  birthDate: string;
  address: string;
  photoUrl: string;
  baseSalary: number;
  positionAllowance: number; // Tunjangan Jabatan (Fixed)
}

export type JobHistoryType = 'PROMOSI' | 'DEMOSI' | 'MUTASI' | 'SANKSI';

export interface JobHistoryRecord {
  id: string;
  employeeId: string;
  type: JobHistoryType;
  previousPosition: string;
  newPosition: string;
  previousSalary: number;
  newSalary: number;
  effectiveDate: string;
  notes: string;
}

export interface SalaryConfig {
  overtimeRatePerHour: number;
  transportPerDay: number;
  deductionPerAbsent: number;
  bonusThreshold: number;
  bonusAmount: number;
}

export interface AttendanceRecord {
  id: string;
  employeeId: string;
  date: string;
  checkIn: string; // "HH:mm"
  checkOut: string; // "HH:mm"
  totalHours: number;
  overtimeHours: number;
  shift: 'PAGI' | 'SIANG' | 'MALAM';
}

export interface PerformanceRecord {
  id: string;
  employeeId: string;
  period: string; // "YYYY-MM"
  permissionCount: number; // Izin
  absentCount: number; // Mangkir (Alpha)
  rating: number; // 0-100
  notes: string;
}

export interface SalarySlip {
  id: string;
  employeeId: string;
  period: string; // "YYYY-MM"
  generatedAt: string;
  
  // Earnings
  baseSalary: number;
  positionAllowance: number; // New component
  overtimePay: number; // Rate * overtimeHours
  performanceBonus: number;
  transportAllowance: number;
  
  // Details for calculation
  totalAttendanceDays: number;
  totalOvertimeHours: number;
  performanceScore: number;
  
  // Deductions
  deductions: number; // e.g. based on absent count
  
  totalSalary: number;
  aiComment?: string; // Generated by Gemini
}

export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  EMPLOYEES = 'EMPLOYEES',
  ATTENDANCE = 'ATTENDANCE',
  PERFORMANCE = 'PERFORMANCE',
  PAYROLL = 'PAYROLL',
  REPORTS = 'REPORTS',
  SETTINGS = 'SETTINGS'
}